# Generated by Django 5.0.4 on 2024-05-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(default='CSE', max_length=100),
        ),
    ]
